### ISSUE TITLE
Migrate to v4 of express

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb-example-nodejs-chat#9]
We're still on v3, and some of the APIs have changed. We should migrate when we get the chance.

Here is the express migration guide: https://github.com/visionmedia/express/wiki/Migrating-from-3.x-to-4.x

**Comment by danielmewes** [comment]
Closed by https://github.com/rethinkdb/rethinkdb-example-nodejs-chat/pull/18
